using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CommonHelper
{
    public static class UserScreenLimidations
    {
        public static bool SaleInvoice;
        public static bool SaleReturnInvoice;
        public static bool FindSaleInvoice;
        public static bool ProformaInvoice;
        public static bool PosScreen;
        public static bool PosShortcuts;
        public static bool PurchaseInvoice;
        public static bool PurchaseReturnInvoice;
        public static bool FindPurchaseInvoice;
        public static bool OrderInvoice;
        public static bool ItemCard;
        public static bool PrimaryInfo;
        public static bool OpeningStock;
        public static bool InventoryAdjustment;
        public static bool SpoiledItems;
        public static bool AgentFile;
        public static bool DeptAdjustment;
        public static bool Debts;
        public static bool BalanceSheet;
        public static bool ReceiveReceipt;
        public static bool PayReceipt;
        public static bool Spending;
        public static bool Drawings;
        public static bool CashCapital;
        public static bool BankDeposit;
        public static bool BankWithdraw;
        public static bool GenPrintBarcode;
        public static bool Users;
        public static bool TimeAttandance;
        public static bool PaySalary;
        public static bool Notes;
        public static bool UserTracking;
        public static bool Reports ;
        public static bool Option;
        public static bool GeneralDiscount;
        public static bool EndOfDays;
        public static bool FirstPrice;
        public static bool WholeSale;
        public static bool MinimumPrice;
        public static bool DateModification;
        public static bool ModifyInvoice;
        public static bool ModifyTodayInvoice;
        public static bool ModifyPrices;
        public static bool TotalField;
        public static bool SubTotalField;
        public static bool InvoiceNavigation;
        public static bool DiscountPerc;
        public static bool DiscountAmt;
        public static bool InvoiceNotes;
        public static bool ExtraCost;
        public static bool Export;
        public static bool Import;
        public static bool ItemCost;
        public static bool InvPayReceipt;
        public static bool InvReceiveReceipt;
        public static bool InvTotalFields;
        public static bool PrintBarcode;
        public static bool Print;
        public static bool DeleteItem;
        public static bool ModifyCost;
        public static bool ModifyQty;
        public static bool ItemInfo;
        public static bool RestoreBackUp;
        public static bool CleanDB;
        public static bool OptionTabGeneral;
        public static bool OptionTabInvoice;
        public static bool OptionTabPrint;
        public static bool OptionTabItem;
        public static bool OptionTabBackUp;
        public static bool OptionTabPeripherals;
        public static bool OptionTabTax;
        public static bool OptionTabNotification;
        public static bool OptionTabOthers;
        public static bool OptionTabChangePass;
        public static bool StartNewYear;
        public static bool SalaryPayment;
        public static bool SaveBackUp;
        public static bool CashDrawer;
        public static bool Accounts;
        public static bool Employee;
    }
}
